import test from 'node:test';
import assert from 'node:assert/strict';
import { JSDOM } from 'jsdom';
import { mount, validateModel } from '../src/index.js';
const graph={nodes:[{id:'a',label:'<script>unsafe</script>',domain:'architecture',types:['Activity']},{id:'b',label:'CEO',domain:'architecture',types:['Person']}],edges:[{source:'a',target:'b',predicate:'assignedTo'}]};
function environment(){const dom=new JSDOM('<main><section id="a"></section><section id="b"></section></main>');globalThis.document=dom.window.document;return dom.window.document;}
const run={kind:'workflow',plan:{nodes:[{id:'inspect',op:'neighbors'},{id:'review',op:'pause'}],edges:[{from:'inspect',to:'review'}]},result:{status:'paused',pending:['review'],trace:[{step:1,active:['inspect'],changed:[]},{step:2,active:['review'],changed:[]}]}};
test('input graph rejects duplicate IDs and dangling edges',()=>{assert.throws(()=>validateModel({nodes:[graph.nodes[0],graph.nodes[0]],edges:[]}));assert.throws(()=>validateModel({nodes:graph.nodes,edges:[{source:'a',target:'missing'}]}));});
test('two instances preserve independent selection, markers and teardown',()=>{const d=environment(),events=[],a=mount(d.querySelector('#a'),{model:graph,onSelect:id=>events.push(id)}),b=mount(d.querySelector('#b'),{model:graph});d.querySelector('#a svg [aria-label="CEO"]').dispatchEvent(new d.defaultView.MouseEvent('click'));assert.equal(a.getState().selected,'b');assert.equal(b.getState().selected,null);assert.deepEqual(events,['b']);const markers=[...d.querySelectorAll('marker')].map(x=>x.id);assert.equal(new Set(markers).size,2);assert.equal(d.querySelectorAll('script').length,0);a.destroy();assert.equal(d.querySelector('#a').children.length,0);assert.equal(d.querySelector('#b').children.length,1);assert.throws(()=>a.setLayout('community'));b.destroy();});
test('keyboard activation, model replacement and route validation work without mutating source',()=>{const d=environment(),v=mount(d.querySelector('#a'),{model:graph});d.querySelector('svg [aria-label="CEO"]').dispatchEvent(new d.defaultView.KeyboardEvent('keydown',{key:'Enter'}));assert.equal(v.getState().layout,'orbit');assert.throws(()=>v.setRoute(['missing']));v.setRoute(['a','b']);v.setPredicate('assignedTo');v.setModel({nodes:[graph.nodes[0]],edges:[]});assert.equal(v.getState().selected,null);assert.equal(graph.nodes.length,2);v.destroy();});
test('recorded workflow replay emits a step selection without runtime execution',()=>{const d=environment(),steps=[],v=mount(d.querySelector('#a'),{model:graph,computation:run,layout:'river',onStep:s=>steps.push(s)});d.querySelector('svg [aria-label="inspect · step 1"]').dispatchEvent(new d.defaultView.MouseEvent('click'));assert.equal(v.getState().step,1);assert.deepEqual(steps,[1]);v.setLayout('flow');assert.match(d.querySelector('[data-ui="layout-count"]').textContent,/step 1/);assert.throws(()=>v.setStep(3));assert.equal(run.result.status,'paused');v.destroy();});
test('malformed trace and oversized workflow are refused before rendering',()=>{const d=environment();assert.throws(()=>mount(d.querySelector('#a'),{model:graph,computation:{...run,result:{trace:[{step:3,active:['inspect']}]}}}));assert.equal(d.querySelector('#a').children.length,0);assert.throws(()=>mount(d.querySelector('#a'),{model:graph,computation:{...run,plan:{nodes:Array.from({length:129},(_,i)=>({id:''+i,op:'set'})),edges:[]}}}));});
test('English is default regardless of document language; Japanese data labels remain intact',()=>{const d=environment();d.documentElement.lang='ja';const jpGraph={...graph,nodes:[{...graph.nodes[0],label:'契約承認'},graph.nodes[1]]};const v=mount(d.querySelector('#a'),{model:jpGraph});assert.equal(d.querySelector('.mithril-graph-viewer').lang,'en');assert.equal(d.querySelector('h2').textContent,'Community Atlas');assert.ok(d.querySelector('nav').textContent.includes('Overview'));assert.equal(v.getState().locale,'en');v.select('a');assert.equal(d.querySelector('h2').textContent,'Focus Orbits');assert.ok(d.querySelector('.stage>svg').textContent.includes('契約承認'));v.setLocale('ja');assert.equal(d.querySelector('h2').textContent,'フォーカス・オービット');assert.equal(d.querySelector('.mithril-graph-viewer').lang,'ja');v.setLocale('en');assert.equal(d.querySelector('h2').textContent,'Focus Orbits');assert.throws(()=>v.setLocale('fr'));assert.equal(v.getState().locale,'en');v.destroy();});
test('explicit locale applies to empty states, group labels, workflow lanes and history',()=>{const d=environment(),a=mount(d.querySelector('#a'),{model:graph}),b=mount(d.querySelector('#b'),{model:graph,locale:'ja'});a.setLayout('flow');assert.ok(d.querySelector('#a').textContent.includes('No record'));assert.equal(b.getState().locale,'ja');a.setComputation(run);assert.ok(d.querySelector('#a .stage>svg').textContent.includes('Read graph'));assert.ok(d.querySelector('#a .stage>svg').textContent.includes('Green: executed'));a.setLayout('river');assert.equal(d.querySelector('#a h2').textContent,'Execution history');assert.equal(d.querySelector('#b h2').textContent,'コミュニティ・アトラス');a.destroy();b.destroy();});
