/* SVG presentation adapter; calculations remain in engine/runtime. */
import * as L from './layout.js';
'use strict';
const NS='http://www.w3.org/2000/svg';
const svg=(tag,attrs={},text)=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;};
function wrapped(text,width,font=13,maxLines=2){const lines=[''];let used=0;for(const c of [...text]){const size=c.charCodeAt(0)>255?font:font*.55;if(used+size>width){if(lines.length===maxLines){lines[lines.length-1]=lines.at(-1).slice(0,-1)+'…';break;}lines.push('');used=0;}lines[lines.length-1]+=c;used+=size;}return lines;}
function textLines(parent,text,x,y,width=130,font=13,attrs={}){const node=svg('text',{x,y,'font-size':font,...attrs});wrapped(text,width,font).forEach((line,i)=>node.append(svg('tspan',{x,dy:i?font+3:0},line)));parent.append(node);return node;}
function marker(canvas,id){const defs=svg('defs'),m=svg('marker',{id,viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:5,markerHeight:5,orient:'auto'});m.append(svg('path',{d:'M0 1 L9 5 L0 9 Z',fill:'context-stroke'}));defs.append(m);canvas.append(defs);}
function button(node,callback,label){node.setAttribute('role','button');node.setAttribute('tabindex','0');node.setAttribute('aria-label',label);node.addEventListener('click',callback);node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();callback();}});}
function routePairs(route){const pairs=new Set();for(let i=1;i<(route?.path?.length||0);i++){pairs.add(route.path[i-1]+'\n'+route.path[i]);pairs.add(route.path[i]+'\n'+route.path[i-1]);}return pairs;}
export function draw(canvas,ctx){
 const {model,layout,selected,scope,group,route,highlight,computation,step,onSelect,onGroup,onStep}=ctx,byId=new Map(model.nodes.map(n=>[n.id,n]));
 if(!['community','orbit','flow','river'].includes(layout))return false;
 canvas.replaceChildren();canvas.setAttribute('viewBox','0 0 1000 630');canvas.setAttribute('width','1000');canvas.setAttribute('height','630');const stage=canvas.parentElement;stage.classList.remove('long-map');marker(canvas,ctx.markerId);
 const setInfo=(title,count,note)=>{ctx.ui.querySelector('[data-ui="layout-title"]').textContent=title;ctx.ui.querySelector('[data-ui="layout-count"]').textContent=count;ctx.ui.querySelector('[data-ui="layout-note"]').textContent=note;};
 const message=text=>canvas.append(svg('text',{x:60,y:220,class:'map-message'},text));
 if(layout==='flow'){
  if(computation?.kind!=='workflow'){setInfo('実行フロー','未実行','ホストアプリから setComputation() で状態付き実行の記録を渡してください。');message('実行すると、分岐・合流・中断の流れを表示します');return true;}
  const f=L.flow(computation.plan),trace=computation.result.trace||[],active=new Set(trace[step-1]?.active||[]),done=new Set(trace.slice(0,step).flatMap(t=>t.active)),pending=new Set(computation.result.pending||[]),position=new Map(f.nodes.map(n=>[n.id,n]));
  canvas.setAttribute('viewBox',`0 0 ${f.width} ${f.height}`);canvas.setAttribute('width',f.width);canvas.setAttribute('height',f.height);stage.classList.add('long-map');stage.style.setProperty('--map-width',f.width+'px');
  setInfo('実行フロー',`${f.nodes.length} 処理 · step ${step}`,`状態付き実行の定義と記録。${computation.result.status} · 横スクロールで全体を確認できます。`);
  for(const lane of f.lanes){canvas.append(svg('rect',{x:25,y:lane.y,width:f.width-50,height:lane.height-8,rx:18,fill:'#f6f8fc'}));textLines(canvas,lane.label,45,lane.y+30,125,14,{fill:'#758398'});}
  const defs=svg('defs'),pattern=svg('pattern',{id:'flow-dots',width:15,height:15,patternUnits:'userSpaceOnUse'});pattern.append(svg('circle',{cx:2,cy:2,r:1,fill:'#dce4ed'}));defs.append(pattern);canvas.append(defs);
  for(const e of f.edges){const a=position.get(e.from),b=position.get(e.to),loop=b.column<=a.column;const x1=a.x+175,y1=a.y+28,x2=b.x,y2=b.y+28;const d=loop?`M ${x1} ${y1} C ${x1+55} ${y1-66}, ${x2-55} ${y2-66}, ${x2} ${y2}`:`M ${x1} ${y1} C ${x1+30} ${y1}, ${x2-30} ${y2}, ${x2} ${y2}`;const edge=svg('path',{d,fill:'none',stroke:active.has(e.from)||active.has(e.to)?'#e77e65':'#b8c8d8','stroke-width':1.7,'marker-end':`url(#${ctx.markerId})`,...(e.when?{'stroke-dasharray':'4 4'}:{})});edge.append(svg('title',{},e.when?`${e.from} → ${e.to} · ${e.when.key} ${e.when.op} ${e.when.value??''}`:`${e.from} → ${e.to}`));canvas.append(edge);}
  for(const n of f.nodes){const color=active.has(n.id)?'#e77e65':done.has(n.id)?'#368f83':pending.has(n.id)?'#d79e4a':'#93a5b8',card=svg('g',{class:'workflow-card'});card.append(svg('rect',{x:n.x,y:n.y,width:175,height:65,rx:12,fill:'#fff',stroke:color,'stroke-width':active.has(n.id)?2.5:1.2}),svg('circle',{cx:n.x+17,cy:n.y+20,r:4,fill:color}));textLines(card,n.id,n.x+30,n.y+25,132,14);card.append(svg('text',{x:n.x+16,y:n.y+51,'font-size':11,fill:'#8291a4'},n.op+(n.cycle?' · 循環':'')));card.append(svg('title',{},JSON.stringify(n)));button(card,()=>{const event=trace.find(t=>t.active.includes(n.id));if(event)onStep(event.step);},n.id+' · '+n.op);canvas.append(card);}
  canvas.append(svg('text',{x:28,y:35,'font-size':15,fill:'#43596f'},'READ → UPDATE → COMMIT'));canvas.append(svg('text',{x:28,y:55,'font-size':11,fill:'#7790a4'},'緑：実行済み · コーラル：選択したステップ · 黄：保存された次の処理'));return true;
 }
 if(layout==='river'){
  if(!computation?.result?.trace?.length){setInfo('実行履歴','未実行','計算を実行すると、記録された同期ステップを再生できます。');message('実行記録を選んで、時間の流れを辿ります');return true;}
  const h=L.history(computation.result),rows=h.steps,actors=h.actors.slice(0,12),workflow=computation.kind==='workflow';
  const width=Math.min(h.width,200+Math.min(rows.length,32)*155),height=Math.max(630,140+Math.max(actors.length,3)*82);canvas.setAttribute('viewBox',`0 0 ${width} ${height}`);canvas.setAttribute('width',width);canvas.setAttribute('height',height);stage.classList.add('long-map');stage.style.setProperty('--map-width',width+'px');
  const start=Math.max(0,Math.min(Math.max(0,rows.length-32),step-16)),visible=rows.slice(start,start+32);
  setInfo('実行履歴',`step ${step} / ${rows.length}`,workflow?'記録された処理の実行。最大12処理・32ステップを表示。ステップを選んで辿れます。':'同期ステップごとの更新・メッセージ数。頂点の途中の値は推定しません。');
  const names=workflow?actors:['実行した頂点','更新した頂点','送信メッセージ'];names.forEach((name,i)=>{const y=105+i*82;canvas.append(svg('rect',{x:22,y,width:width-44,height:72,rx:16,fill:i%2?'#f4f1fc':'#eff7f5'}));textLines(canvas,name,40,y+34,105,13,{fill:'#6d8294'});});
  for(let j=0;j<visible.length;j++){const r=visible[j],x=175+j*155,selectedStep=r.step===step;canvas.append(svg('text',{x:x+15,y:73,'font-size':13,fill:selectedStep?'#e77e65':'#7790a4'},'STEP '+r.step));if(selectedStep)canvas.append(svg('line',{x1:x+49,y1:90,x2:x+49,y2:height-45,stroke:'#e77e65','stroke-width':2,'stroke-dasharray':'4 5'}));
    if(workflow){for(let i=0;i<actors.length;i++){const actor=actors[i];if(!r.actors.includes(actor))continue;const y=120+i*82,card=svg('g');card.append(svg('rect',{x,y,width:112,height:42,rx:12,fill:selectedStep?'#fff0ea':'#fff',stroke:selectedStep?'#e77e65':'#c9ddd7'}));textLines(card,actor,x+10,y+25,92,12,{fill:'#456556'});button(card,()=>onStep(r.step),actor+' · step '+r.step);canvas.append(card);const prior=visible.slice(0,j).map((t,k)=>({t,k})).reverse().find(v=>v.t.actors.includes(actor));if(prior)canvas.append(svg('path',{d:`M ${175+prior.k*155+112} ${y+21} C ${175+prior.k*155+140} ${y+21}, ${x-22} ${y+21}, ${x} ${y+21}`,fill:'none',stroke:'#c1d6cf','stroke-width':2}));}}
    else [r.activeCount,r.changed,r.messages].forEach((value,i)=>{const card=svg('g');card.append(svg('rect',{x,y:120+i*82,width:112,height:42,rx:12,fill:selectedStep?'#fff0ea':'#fff',stroke:selectedStep?'#e77e65':'#cad8e3'}),svg('text',{x:x+15,y:147+i*82,'font-size':17,fill:'#43596f'},String(value)));button(card,()=>onStep(r.step),'step '+r.step+' · '+names[i]+' '+value);canvas.append(card);});}
  return true;
 }
 let p;if(layout==='community'){
  p=L.community(scope,model.edges,{group,priority:[selected,...route?.path||[]]});setInfo(group?(L.groups.find(g=>g.id===group)?.label||'グループ'):'コミュニティ・アトラス',`${p.shown} / ${p.total.toLocaleString()} ノード`,group?'このグループの代表36件まで。全件は下の検索と隣接関係から辿れます。':'型と所属によるグループ。代表ノードを選ぶと周辺を展開します。');
  const regionById=new Map(p.regions.map(r=>[r.id,r]));
  for(const bridge of p.bridges.sort((a,b)=>b.count-a.count).slice(0,6)){const a=regionById.get(bridge.source),b=regionById.get(bridge.target),ax=a.x+a.w/2,ay=a.y+a.h/2,bx=b.x+b.w/2,by=b.y+b.h/2;canvas.append(svg('path',{d:`M ${ax} ${ay} C ${ax} ${(ay+by)/2}, ${bx} ${(ay+by)/2}, ${bx} ${by}`,fill:'none',stroke:'#bbcddd','stroke-width':Math.min(5,1+Math.log1p(bridge.count)/3),opacity:.45}));}
  for(const r of p.regions){const card=svg('g',{class:'cluster-hit'});card.append(svg('rect',{x:r.x,y:r.y,width:r.w,height:r.h,rx:32,fill:r.fill,stroke:r.color,'stroke-opacity':.18}),svg('circle',{cx:r.x+24,cy:r.y+25,r:4,fill:r.color}),svg('text',{x:r.x+36,y:r.y+31,'font-size':16,'font-weight':650,fill:r.color},r.label),svg('text',{x:r.x+r.w-21,y:r.y+31,'text-anchor':'end','font-size':13,fill:r.color},r.total.toLocaleString()));button(card,()=>onGroup(r.id),r.label+' · '+r.total+'件をひらく');canvas.append(card);if(r.total>r.shown)canvas.append(svg('text',{x:r.x+22,y:r.y+r.h-10,'font-size':11,fill:r.color},`+ ${(r.total-r.shown).toLocaleString()} 件 · グループをひらく`));}
 }else{
  if(!selected){setInfo('フォーカス・オービット','未選択','検索か全体図から、中心にするノードを選んでください。');message('ノードを選ぶと、関係がここに広がります');return true;}
  p=L.orbit(model,selected,{predicate:ctx.predicate,priority:route?.path||[]});setInfo('フォーカス・オービット',`隣接 ${p.shownFirst} / ${p.totalFirst} 件`,`全グラフの周辺を表示 · 1 hop ${p.totalFirst} 件、選んだ隣接ノードの2 hop候補 ${p.totalSecond} 件 · 表示は隣接8件・2 hop候補12件まで。`);
  for(const radius of [185,277])canvas.append(svg('circle',{cx:500,cy:318,r:radius,fill:'none',stroke:'#e3ebf3','stroke-dasharray':radius===277?'3 7':'none'}));canvas.append(svg('text',{x:500,y:45,'text-anchor':'middle','font-size':11,fill:'#99aabd'},'2 HOPS · CONTEXT'));
 }
 const pos=new Map(p.points.map(pt=>[pt.id,pt])),pairs=routePairs(route);const edges=p.edges.filter(e=>layout==='orbit'||e.source===selected||e.target===selected||pairs.has(e.source+'\n'+e.target));
 for(const e of edges.slice(0,80)){const a=pos.get(e.source),b=pos.get(e.target);if(!a||!b)continue;const focused=e.source===selected||e.target===selected||pairs.has(e.source+'\n'+e.target),dx=b.x-a.x,dy=b.y-a.y,length=Math.hypot(dx,dy)||1,sx=a.x+dx*12/length,sy=a.y+dy*12/length,tx=b.x-dx*12/length,ty=b.y-dy*12/length;
  const line=svg('path',{d:`M ${sx} ${sy} Q ${(sx+tx)/2-dy*.08} ${(sy+ty)/2+dx*.08} ${tx} ${ty}`,fill:'none',class:'map-edge',stroke:focused?'#d88671':'#bbcddb','stroke-width':focused?1.9:1.1,opacity:focused?.85:.45,'marker-end':`url(#${ctx.markerId})`});line.append(svg('title',{},`${byId.get(e.source)?.label} → ${byId.get(e.target)?.label} · ${e.predicate}`));canvas.append(line);}
 for(const point of p.points){const n=byId.get(point.id),g=L.groups.find(g=>g.id===L.groupFor(n)),focus=n.id===selected,node=svg('g',{class:'node'+(focus?' selected':'')});const circle=svg('circle',{cx:point.x,cy:point.y,r:layout==='orbit'&&focus?29:8,fill:focus?'#fff3ed':highlight.has(n.id)?'#edb263':g.color,stroke:focus?'#e77e65':'#fff','stroke-width':focus?3:2});node.append(circle,svg('title',{},`${n.label}\n${n.id}`));button(node,()=>onSelect(n.id),n.label);canvas.append(node);}
 const labels=L.labels(p.points,byId,{center:layout==='orbit'?selected:null});for(const label of labels){if(layout==='orbit'&&label.id===selected)continue;const n=byId.get(label.id),groupNode=svg('g',{class:'map-label'});groupNode.append(svg('rect',{x:label.x-3,y:label.y-2,width:label.w+6,height:label.h,rx:5,fill:'#fff','fill-opacity':layout==='orbit'?.9:0}));textLines(groupNode,n.label,label.x,label.y+12,label.w,13,{fill:'#3e5367'});canvas.append(groupNode);}
 if(layout==='orbit'&&selected){const n=byId.get(selected);textLines(canvas,n.label,500,370,180,17,{'text-anchor':'middle','font-weight':650,fill:'#374f64'});canvas.append(svg('text',{x:500,y:319,'text-anchor':'middle','font-size':13,fill:'#d57c62'},'●'));}
 return true;
}
